<a href="https://colab.research.google.com/github/kirtika8953/Deep-Learning-for-Sentiment-Analysis-/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/survey.csv")

In [ ]:
display(df.columns)

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [ ]:
df = df.drop('Country', axis=1)
display(df.head())

,Timestamp,Age,Gender,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,27-08-2014 11:29,37,Female,IL,NaN,No,Yes,Often,Jun-25,No,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,27-08-2014 11:29,44,M,IN,NaN,No,No,Rarely,More than 1000,No,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,27-08-2014 11:29,32,Male,NaN,NaN,No,No,Rarely,Jun-25,No,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,27-08-2014 11:29,31,Male,NaN,NaN,Yes,Yes,Often,26-100,No,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,27-08-2014 11:30,31,Male,TX,NaN,No,No,Never,100-500,Yes,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [ ]:
df = df.drop('state', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,Jun-25,No,Yes,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,Jun-25,No,Yes,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [ ]:
df = df.drop('mental_vs_physical', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,Jun-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,Jun-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,No,NaN

In [ ]:
df = df.drop('coworkers', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,Jun-25,No,Yes,...,Yes,Yes,Somewhat easy,No,No,Yes,No,Maybe,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,Jun-25,No,Yes,...,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,No,Somewhat difficult,Yes,Yes,No,Maybe,Maybe,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,Don't know,No,No,Yes,Yes,Yes,No,NaN

In [ ]:
df = df.drop('no_employees', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,...,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,No,Yes,Yes,...,Yes,Yes,Somewhat easy,No,No,Yes,No,Maybe,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,No,No,Don't know,...,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,No,Yes,No,...,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,No,Yes,No,...,No,No,Somewhat difficult,Yes,Yes,No,Maybe,Maybe,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,Yes,Yes,Yes,...,Don't know,Don't know,Don't know,No,No,Yes,Yes,Yes,No,NaN

In [ ]:
df = df.drop('anonymity', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,...,wellness_program,seek_help,leave,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,No,Yes,Yes,...,No,Yes,Somewhat easy,No,No,Yes,No,Maybe,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,No,No,Don't know,...,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,No,Yes,No,...,No,No,Somewhat difficult,No,No,Yes,Yes,Yes,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,No,Yes,No,...,No,No,Somewhat difficult,Yes,Yes,No,Maybe,Maybe,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,Yes,Yes,Yes,...,Don't know,Don't know,Don't know,No,No,Yes,Yes,Yes,No,NaN

In [ ]:
df = df.drop('leave', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,Yes,No,Maybe,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No,No,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes,Yes,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,No,Maybe,Maybe,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes,Yes,No,NaN

In [ ]:
df = df.drop('supervisor', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview,obs_consequence,comments
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe,No,NaN
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No,No,NaN
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes,No,NaN
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe,Yes,NaN
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes,No,NaN

In [ ]:
df = df.drop('comments', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview,obs_consequence
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe,No
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No,No
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes,No
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe,Yes
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes,No

In [ ]:
df = df.drop('obs_consequence', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,Female,NaN,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,M,NaN,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,Male,NaN,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,Male,NaN,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,Male,NaN,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df.to_csv('data1.csv', index=False)

In [ ]:
def map_gender(gender):
    if gender == 'Male':
        return 1
    elif gender == 'Female':
        return 2
    else:
        return 0

df['Gender'] = df['Gender'].apply(map_gender)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,NaN,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,NaN,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,NaN,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,NaN,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,NaN,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
display(df.isnull().sum())

Timestamp                      0
Age                            0
Gender                         0
self_employed                 18
family_history                 0
treatment                      0
work_interfere               264
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
mental_health_consequence      0
phys_health_consequence        0
mental_health_interview        0
phys_health_interview          0
dtype: int64

In [ ]:
for col in ['self_employed', 'work_interfere']:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)

display(df.isnull().sum())

/tmp/ipython-input-156177984.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_val, inplace=True)

Timestamp                    0
Age                          0
Gender                       0
self_employed                0
family_history               0
treatment                    0
work_interfere               0
remote_work                  0
tech_company                 0
benefits                     0
care_options                 0
wellness_program             0
seek_help                    0
mental_health_consequence    0
phys_health_consequence      0
mental_health_interview      0
phys_health_interview        0
dtype: int64

In [ ]:
df.to_csv('data2.csv', index=False)

In [ ]:
df = df[(df['Age'] >= 0) & (df['Age'] <= 100)]
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,No,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,No,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,No,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,No,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,No,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df['self_employed'] = df['self_employed'].map({'Yes': 1, 'No': 0})
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,No,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,No,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,No,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,Yes,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,No,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df['family_history'] = df['family_history'].map({'Yes': 1, 'No': 0})
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,Yes,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,No,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,No,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,Yes,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,No,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df['treatment'] = df['treatment'].map({'Yes': 1, 'No': 0})
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,Often,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,Rarely,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,Rarely,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,Often,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,Never,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df['work_interfere'] = df['work_interfere'].map({'Often': 1, 'Never': 0, 'Rarely': 2, 'Sometimes': 3})
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,No,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,No,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,No,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,No,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,Yes,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df['remote_work'] = df['remote_work'].map({'Yes': 1, 'No': 0})
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,Yes,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,No,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,Yes,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,Yes,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,Yes,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
df['tech_company'] = df['tech_company'].map({'Yes': 1, 'No': 0})
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,Yes,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,Don't know,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,No,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,No,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,Yes,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
def map_benefits(benefit):
    if benefit == 'Yes':
        return 1
    else:
        return 0

df['benefits'] = df['benefits'].apply(map_benefits)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,Not sure,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,No,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,No,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,Yes,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,No,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
def map_care_options(care_option):
    if care_option == 'Yes':
        return 1
    else:
        return 0

df['care_options'] = df['care_options'].apply(map_care_options)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,No,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,Don't know,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,No,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,No,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,Don't know,Don't know,No,No,Yes,Yes

In [ ]:
def map_wellness_program(program):
    if program == 'Yes':
        return 1
    else:
        return 0

df['wellness_program'] = df['wellness_program'].apply(map_wellness_program)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,0,Yes,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,0,Don't know,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,0,No,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,0,No,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,0,Don't know,No,No,Yes,Yes

In [ ]:
def map_seek_help(help_option):
    if help_option == 'Yes':
        return 1
    else:
        return 0

df['seek_help'] = df['seek_help'].apply(map_seek_help)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,0,1,No,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,0,0,Maybe,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,0,0,No,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,0,0,Yes,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,0,0,No,No,Yes,Yes

In [ ]:
def map_mental_health_consequence(consequence):
    if consequence == 'Yes':
        return 1
    else:
        return 0

df['mental_health_consequence'] = df['mental_health_consequence'].apply(map_mental_health_consequence)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,0,1,0,No,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,0,0,0,No,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,0,0,0,No,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,0,0,1,Yes,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,0,0,0,No,Yes,Yes

In [ ]:
def map_phys_health_consequence(consequence):
    if consequence == 'Yes':
        return 1
    else:
        return 0

df['phys_health_consequence'] = df['phys_health_consequence'].apply(map_phys_health_consequence)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,0,1,0,0,No,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,0,0,0,0,No,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,0,0,0,0,Yes,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,0,0,1,1,Maybe,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,0,0,0,0,Yes,Yes

In [ ]:
def map_mental_health_interview(interview):
    if interview == 'Yes':
        return 1
    else:
        return 0

df['mental_health_interview'] = df['mental_health_interview'].apply(map_mental_health_interview)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview,phys_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,0,1,0,0,0,Maybe
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,0,0,0,0,0,No
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,0,0,0,0,1,Yes
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,0,0,1,1,0,Maybe
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,0,0,0,0,1,Yes

In [ ]:
df = df.drop('phys_health_interview', axis=1)
display(df.head())

,Timestamp,Age,Gender,self_employed,family_history,treatment,work_interfere,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,mental_health_consequence,phys_health_consequence,mental_health_interview
0,27-08-2014 11:29,37,2,0,0,1,1,0,1,1,0,0,1,0,0,0
1,27-08-2014 11:29,44,0,0,0,0,2,0,0,0,0,0,0,0,0,0
2,27-08-2014 11:29,32,1,0,0,0,2,0,1,0,0,0,0,0,0,1
3,27-08-2014 11:29,31,1,0,1,1,1,0,1,0,1,0,0,1,1,0
4,27-08-2014 11:30,31,1,0,0,0,0,1,1,1,0,0,0,0,0,1

In [ ]:
df.to_csv('data3.csv', index=False)